# Generated by Django 4.2.6 on 2023-10-25 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('born_date', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('rg', models.CharField(max_length=9)),
                ('legal_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_person_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JuridicPerson',
            fields=[
                ('state_registration', models.CharField(max_length=11)),
                ('open_date', models.CharField(max_length=10)),
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('juridic_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juridic_person_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.IntegerField()),
                ('number', models.IntegerField()),
                ('number_verificate', models.IntegerField()),
                ('type_account', models.CharField(max_length=20)),
                ('limit', models.IntegerField()),
                ('active', models.BooleanField()),
                ('juridic_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kebank.juridicperson')),
                ('legal_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kebank.legalperson')),
            ],
        ),
    ]
