# Generated by Django 4.2.6 on 2023-12-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='Kebank/images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
