# Generated by Django 4.2.6 on 2023-12-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentation',
            name='type_movimentation',
            field=models.CharField(choices=[('P', 'Pix'), ('Pix cartão de crédito', 'Pix cartão crédito'), ('Empréstimo', 'Empréstimo')], default='Pix', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='Kebank/images/%Y/%m/%d/'),
        ),
    ]
