# Generated by Django 4.2.6 on 2023-12-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentation',
            name='credit_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credit_movimentation', to='Kebank.creditcard'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PixCreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observation', models.CharField(max_length=100)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='Kebank.creditcard')),
            ],
        ),
    ]
