# Generated by Django 4.2.6 on 2023-11-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0002_alter_creditcard_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='validity',
            field=models.DateField(),
        ),
    ]
