# Generated by Django 4.2.6 on 2023-12-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0003_movimentation_credit_card_pixcreditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentation',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_movimentation', to='Kebank.account'),
        ),
        migrations.AlterField(
            model_name='movimentation',
            name='credit_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_movimentation', to='Kebank.creditcard'),
        ),
        migrations.AlterField(
            model_name='movimentation',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
