# Generated by Django 4.2.6 on 2023-11-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0003_alter_creditcard_validity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='cpf_cnpj',
        ),
    ]
