# Generated by Django 4.2.6 on 2023-10-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0003_user_is_active_user_is_admin_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='agency',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='juridic_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juridic_person_JuridicPerson', to='Kebank.juridicperson'),
        ),
        migrations.AlterField(
            model_name='account',
            name='legal_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_person_LegalPerson', to='Kebank.legalperson'),
        ),
        migrations.AlterField(
            model_name='account',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='number_verificate',
            field=models.IntegerField(blank=True),
        ),
    ]
