# Generated by Django 4.2.6 on 2023-10-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0004_alter_account_active_alter_account_agency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='juridic_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juridic_person_JuridicPerson', to='Kebank.juridicperson'),
        ),
        migrations.AlterField(
            model_name='account',
            name='legal_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_person_LegalPerson', to='Kebank.legalperson'),
        ),
    ]
