# Generated by Django 4.2.6 on 2023-11-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0004_alter_user_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalperson',
            old_name='physical_person',
            new_name='fk_user',
        ),
    ]
