# Generated by Django 4.2.6 on 2023-12-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0004_alter_movimentation_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentation',
            name='account',
        ),
        migrations.AddField(
            model_name='movimentation',
            name='from_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credit_from_account', to='Kebank.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentation',
            name='to_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credit_to_account', to='Kebank.account'),
            preserve_default=False,
        ),
    ]
