# Generated by Django 4.2.6 on 2023-11-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0005_rename_physical_person_physicalperson_fk_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juridicperson',
            old_name='juridic_person',
            new_name='fk_user',
        ),
    ]
