# Generated by Django 4.2.6 on 2023-12-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0005_remove_movimentation_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentation',
            old_name='state',
            new_name='type_movimentation',
        ),
    ]
