# Generated by Django 4.2.6 on 2023-11-15 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0006_rename_juridic_person_juridicperson_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_card', to='Kebank.account'),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_card', models.CharField(blank=True, max_length=20)),
                ('number', models.CharField(blank=True, max_length=16, unique=True)),
                ('validity', models.CharField(blank=True, max_length=7)),
                ('cvv', models.IntegerField(blank=True)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_card_credit', to='Kebank.account')),
            ],
        ),
    ]
