# Generated by Django 4.2.6 on 2023-12-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0006_rename_state_movimentation_type_movimentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentation',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimentation',
            name='type_movimentation',
            field=models.CharField(choices=[('P', 'Pix'), ('CC', 'Pix cartão crédito'), ('L', 'Empréstimo')], max_length=100, null=True),
        ),
    ]
