# Generated by Django 4.2.6 on 2023-12-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0007_movimentation_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentation',
            name='type_movimentation',
            field=models.CharField(choices=[('P', 'Pix'), ('CC', 'Pix cartão crédito'), ('L', 'Empréstimo')], default='P', max_length=100, null=True),
        ),
    ]
