# Generated by Django 4.2.6 on 2023-10-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0007_alter_account_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
