# Generated by Django 4.2.6 on 2023-10-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0009_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('federative_unit', models.CharField(blank=True, max_length=2)),
                ('pac', models.CharField(blank=True, max_length=10)),
                ('public_place', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
