# Generated by Django 4.2.6 on 2023-10-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0010_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='federative_unit',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
