# Generated by Django 4.2.6 on 2023-10-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0011_alter_address_city_alter_address_federative_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='federative_unit',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
