# Generated by Django 4.2.6 on 2023-10-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0013_address_juridic_person_address_legal_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_card', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=16, unique=True)),
                ('validity', models.CharField(max_length=5)),
                ('cvv', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kebank.account')),
            ],
        ),
        migrations.AlterField(
            model_name='juridicperson',
            name='cnpj',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='rg',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.CreateModel(
            name='Movimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hour', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_movimentation', to='Kebank.card')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_solicitation', models.DateTimeField(auto_now_add=True)),
                ('fees', models.DecimalField(decimal_places=1, max_digits=3)),
                ('date_approved', models.DateField(auto_now_add=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved', models.BooleanField()),
                ('installment_quantity', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kebank.account')),
            ],
        ),
    ]
