# Generated by Django 4.2.6 on 2023-10-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0015_alter_card_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='flag_card',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='validity',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
