# Generated by Django 4.2.6 on 2023-10-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0016_alter_card_cvv_alter_card_flag_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.CharField(max_length=10)),
                ('installment_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuition', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_type', models.CharField(max_length=30)),
                ('rentability', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_closure', models.CharField(max_length=10)),
                ('administration_fee', models.DecimalField(decimal_places=2, max_digits=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='Kebank.account')),
            ],
        ),
    ]
