# Generated by Django 4.2.6 on 2023-10-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0017_loaninstallment_investment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegalPerson',
            new_name='PhysicalPerson',
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='loan',
            name='requested_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
