# Generated by Django 4.2.6 on 2023-10-31 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0019_pix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='legal_person',
            new_name='physical_person',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='legal_person',
            new_name='physical_person',
        ),
        migrations.RemoveField(
            model_name='address',
            name='legal_person',
        ),
        migrations.AddField(
            model_name='address',
            name='physical_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_person_address_LegalPerson', to='Kebank.physicalperson'),
        ),
    ]
