# Generated by Django 4.2.6 on 2023-10-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0020_rename_legal_person_account_physical_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentation',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
