# Generated by Django 4.2.6 on 2023-10-31 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0021_alter_movimentation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='juridic_person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juridic_person_JuridicPerson', to='Kebank.juridicperson'),
        ),
        migrations.AlterField(
            model_name='account',
            name='physical_person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_person_LegalPerson', to='Kebank.physicalperson'),
        ),
    ]
