# Generated by Django 4.2.6 on 2023-10-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0022_alter_account_juridic_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='income',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
