# Generated by Django 4.2.6 on 2023-11-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0023_investment_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='administration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='investment',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='rentability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='juridicperson',
            name='open_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='physicalperson',
            name='born_date',
            field=models.DateField(),
        ),
    ]
