# Generated by Django 4.2.6 on 2023-11-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0024_alter_investment_administration_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentation',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_movimentation', to='Kebank.account'),
            preserve_default=False,
        ),
    ]
