# Generated by Django 4.2.6 on 2023-11-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0028_alter_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
