# Generated by Django 4.2.6 on 2023-11-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebank', '0030_remove_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
